Drop table if exists transaction;
Drop table if exists vehicle_plate;
DRop table if exists customer;

-- CUSTOMER TABLE
CREATE TABLE customer (
                          id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username    VARCHAR(255) UNIQUE NOT NULL,
                          password    VARCHAR(255) NOT NULL,
                          first_name  VARCHAR(255),
                          last_name   VARCHAR(255),
                          role VARCHAR(20)
);

-- VEHICLE PLATE TABLE
CREATE TABLE vehicle_plate (
                               plate_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               plate_number   VARCHAR(20) NOT NULL UNIQUE,
                               personalised   BOOLEAN,
                               available      BOOLEAN,
                               price          DOUBLE PRECISION,
                               customer_id    INTEGER,
                               CONSTRAINT fk_vehicle_plate_customer
                                   FOREIGN KEY (customer_id) REFERENCES customer(id)
);

-- INDEX on plate_number
CREATE INDEX idx_plate_number
    ON vehicle_plate (plate_number);

-- TRANSACTION TABLE
CREATE TABLE transaction (
                             transaction_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             customer_id       INTEGER,
                             vehicle_plate_id  INTEGER,
                             price_paid        DOUBLE PRECISION,
                             transaction_date  DATE,
                             CONSTRAINT fk_tx_customer
                                 FOREIGN KEY (customer_id)       REFERENCES customer(id),
                             CONSTRAINT fk_tx_vehicle_plate
                                 FOREIGN KEY (vehicle_plate_id)  REFERENCES vehicle_plate(plate_id)
);





INSERT INTO customer (username, password, first_name, last_name, role) VALUES
                                                                         ('jdoe', 'password123', 'John', 'Doe', 'CUSTOMER'),
                                                                         ('asmith', 'secret456', 'Alice', 'Smith', 'CUSTOMER'),
                                                                         ( 'bwayne', 'darkknight', 'Bruce', 'Wayne', 'CUSTOMER'),
                                                                         ('ckent', 'superman', 'Clark', 'Kent', 'CUSTOMER'),
                                                                         ('dparker', 'sp1derm4n', 'Peter', 'Parker', 'CUSTOMER');

INSERT INTO vehicle_plate (plate_number, personalised, available, price, customer_id) VALUES
-- Personalised Plates
('MYCAR', true, false, 12468.60, 1),
('LUX 99', true, false, 88012.34, 2),
('GHOST', true, false, 96328.17, 3),
('RK 88', true, false, 50132.45, 4),
('OJH53', true, false, 62879.14, 5),
('AC25 UJC', false, false, 64.52, 1),
('BA17 XYZ', false, false, 91.24, 2),
('CA66 POI', false, false, 70.11, 3),
('DA89 KLM', false, false, 88.02, 4),
('EA12 RTY', false, false, 40.88, 5),
('Z00M', true, true, 78823.21, null),
('GLOBE1', true, true, 18500.00, null),
('DRMR', true, true, 71000.14, null),
('FXN1TE', true, true, 98999.99, null),
('HEL 23', true, true, 1000.00, null),
('FRESHY', true, true, 45000.49, null),
('HZ0N', true, true, 9999.99, null),
('SUN 5H', true, true, 22999.22, null),
('BOSS23', true, true, 80500.35, null),
('R1D3UP', true, true, 68910.88, null),
-- Standard Plates
('FA33 HJU', false, true, 34.90, null),
('GA98 ZXC', false, true, 29.12, null),
('HA71 QWE', false, true, 77.65, null),
('KA44 DFG', false, true, 86.77, null),
('LA26 BNM', false, true, 20.99, null),
('MA84 IOP', false, true, 63.44, null),
('NA61 UYT', false, true, 53.31, null),
('OA19 VBN', false, true, 92.88, null),
('PA76 ASL', false, true, 45.02, null),
('RA88 WER', false, true, 87.00, null),
('SA15 PLM', false, true, 74.31, null),
('MNTY', true, true, 10200.67, null),
('VIP 123', true, true, 90100.10, null),
('GL1CH', true, true, 11200.00, null),
('NV 7', true, true, 45000.00, null),
('SN0W', true, true, 32123.54, null),
('W1NTR', true, true, 79811.60, null),
('CRUZER', true, true, 28900.44, null),
('TRB 88', true, true, 57900.76, null),
('SLK 77', true, true, 88234.19, null),
('RIDEZ', true, true, 19999.99, null),
('VA02 OKM', false, true, 58.99, null),
('WA39 HJK', false, true, 49.32, null),
('YA66 RFT', false, true, 95.73, null),
('AX33 GHT', false, true, 28.00, null),
('BX91 TGB', false, true, 38.42, null),
('CX76 YHN', false, true, 51.89, null),
('DX53 MKL', false, true, 73.65, null),
('EX44 LOP', false, true, 66.71, null),
('FX21 QAZ', false, true, 20.88, null),
('GX12 WSX', false, true, 39.55, null),
('HX23 EDC', false, true, 93.87, null),
('KX45 RFV', false, true, 27.60, null),
('LX99 TGB', false, true, 48.13, null),
('MX01 ZXC', false, true, 77.91, null),
('NX19 BNM', false, true, 99.00, null),
('OX88 VFR', false, true, 64.47, null),
('PX02 JKL', false, true, 33.98, null),
('RX36 UIO', false, true, 68.73, null),
('SX18 MNB', false, true, 59.19, null),
('VX70 QWE', false, true, 42.61, null),
('WX64 ASD', false, true, 83.57, null),
('YX77 ZXC', false, true, 90.10, null),
('AY22 TYU', false, true, 26.00, null),
('BY56 PLK', false, true, 31.73, null),
('CY80 QAZ', false, true, 22.41, null),
('DY11 WSX', false, true, 43.00, null),
('EY67 EDC', false, true, 55.29, null),
('FY23 RFV', false, true, 79.16, null),
('GY88 TGB', false, true, 62.77, null),
('HY71 YHN', false, true, 97.54, null),
('KY29 MKL', false, true, 30.90, null),
('LY16 LOP', false, true, 41.84, null),
('MY04 QAZ', false, true, 69.36, null),
('NY73 WSX', false, true, 86.25, null),
('OY19 EDC', false, true, 36.64, null),
('PY55 RFV', false, true, 84.21, null),
('RY82 TGB', false, true, 23.15, null),
('SY33 YHN', false, true, 46.58, null),
('TY48 MKL', false, true, 58.39, null),
('UY20 LOP', false, true, 60.90, null),
('VY11 QAZ', false, true, 21.14, null),
('WY75 WSX', false, true, 24.67, null),
('YY09 EDC', false, true, 44.92, null);





INSERT INTO transaction (customer_id, vehicle_plate_id, price_paid, transaction_date) VALUES
                                                                                          (1, 1, 776.32, DATE '2025-04-01'),
                                                                                          (1, 2, 62879.14, DATE '2025-04-03'),
                                                                                          (2, 3, 908.45, DATE '2025-04-04'),
                                                                                          (2, 4, 12468.60, DATE '2025-04-06'),
                                                                                          (3, 5, 551.90, DATE '2025-04-08'),
                                                                                          (3, 6, 88012.34, DATE '2025-04-10'),
                                                                                          (4, 7, 725.12, DATE '2025-04-12'),
                                                                                          (4, 8, 96328.17, DATE '2025-04-14'),
                                                                                          (5, 9, 410.83, DATE '2025-04-16'),
                                                                                          (5, 10, 50132.45, DATE '2025-04-18');



UPDATE vehicle_plate
SET available = TRUE
WHERE customer_id IS NULL;

UPDATE vehicle_plate
SET available = FALSE
WHERE customer_id IS NOT NULL;